env:
  - GO111MODULE=on
builds:
  - binary: lntop
    main: ./cmd/lntop/main.go
    flags:
      - -mod=vendor
    env:
      - CGO_ENABLED=0
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
