[logger]
type = "development" # "production"
dest = "/root/.lntop/lntop.log"

[network]
name = "lnd"
type = "lnd"
address = "${LND_GRPC_HOST}"
cert = "/root/aux/tls.cert"
macaroon = "/root/aux/admin.macaroon"
macaroon_timeout = 60
max_msg_recv_size = 52428800
conn_timeout = 1000000
pool_capacity = 3